import { StrategicPlan } from '../types';

export const agencyProductHybridPlan: StrategicPlan = {
  id: 'agency-product-hybrid',
  title: 'Agency to Product Hybrid',
  subtitle: 'Service-led cash flow that incubates a proprietary software product.',
  summary:
    'Launch a specialized agency delivering high-value outcomes while building internal tooling that evolves into a standalone product with embedded expertise.',
  idealFounderProfile: [
    'Senior practitioner with repeatable playbooks in growth, ops, or creative domains',
    'Product-minded operator eager to codify services into reusable software accelerators',
    'Comfort with selling consultative engagements and owning client delivery',
  ],
  capitalAllocations: [
    {
      category: 'Client Delivery Team',
      description: 'Initial hires and contractors to execute engagements with quality.',
      amount: 140000,
      percentage: 35,
    },
    {
      category: 'Product Incubation',
      description: 'Internal tooling, prototyping, and design resources for the product wedge.',
      amount: 90000,
      percentage: 22,
    },
    {
      category: 'Growth & Partnerships',
      description: 'Outbound sales, content, and channel partnerships.',
      amount: 65000,
      percentage: 16,
    },
    {
      category: 'Operations & Runway Buffer',
      description: 'General & administrative, tooling, and 6-month reserve.',
      amount: 105000,
      percentage: 27,
    },
  ],
  phases: [
    {
      id: 'service-design',
      title: 'Service Design & Beachhead',
      duration: 'Months 0-3',
      focus: 'Package signature service offering with clear ICP and value proposition.',
      objectives: [
        'Deliver first three paid engagements with 50%+ gross margin.',
        'Document playbooks and reusable assets for every client deliverable.',
      ],
      milestones: [
        'Client NPS above 50 with documented testimonials.',
        'Internal repository of reusable templates, scripts, and dashboards.',
      ],
      kpisTracked: ['kpi-gm', 'kpi-client-sat'],
    },
    {
      id: 'tooling-incubation',
      title: 'Tooling Incubation',
      duration: 'Months 3-9',
      focus: 'Translate repeatable workflows into internal productized modules.',
      objectives: [
        'Launch minimum lovable tool powering internal delivery efficiency gains.',
        'Capture structured data from every engagement for product roadmap insights.',
      ],
      milestones: [
        'Internal tool reduces delivery time by 30%.',
        'At least five clients opt into pilot access of the tool.',
      ],
      kpisTracked: ['kpi-delivery-cycle', 'kpi-product-adoption'],
    },
    {
      id: 'hybrid-scale',
      title: 'Hybrid Scale & Productization',
      duration: 'Months 9-18',
      focus: 'Introduce subscription-based access and blend services with software.',
      objectives: [
        'Achieve 35% of revenue from recurring retainers or subscriptions.',
        'Build lightweight onboarding and training for self-serve components.',
      ],
      milestones: [
        'Launch tiered pricing that bundles service sprints with product access.',
        'Churn below 5% on hybrid retainers.',
      ],
      kpisTracked: ['kpi-recurring-revenue-share', 'kpi-churn'],
    },
    {
      id: 'product-spinout',
      title: 'Product Spin-Out Readiness',
      duration: 'Months 18-30',
      focus: 'Transition from services-led to product-led growth while maintaining profitability.',
      objectives: [
        'Document customer journeys for self-serve adoption and support.',
        'Identify strategic partners or investors for scaling the software platform.',
      ],
      milestones: [
        'MRR surpasses $100k with 70% gross margin on software component.',
        'Playbook for transitioning service clients to product-first engagements.',
      ],
      kpisTracked: ['kpi-mrr-hybrid', 'kpi-software-margin'],
    },
  ],
  pros: [
    'Services cash flow funds product development without external capital.',
    'Direct client feedback accelerates product-market fit insights.',
    'Flexible engagement models lower churn and increase account stickiness.',
  ],
  cons: [
    'Context switching between client delivery and product build can dilute focus.',
    'Team structure must balance billable utilization with internal R&D.',
    'Valuation multiples lag pure-play SaaS until product revenue dominates.',
  ],
  risks: [
    {
      id: 'risk-utilization',
      title: 'Utilization Volatility',
      description: 'Inconsistent project flow reduces service gross margin and cash buffer.',
      likelihood: 'medium',
      impact: 'material',
      mitigation: ['Maintain rolling 90-day pipeline coverage', 'Use flexible contractor bench'],
      contingency: 'Throttle product investment temporarily to restore cash position.',
    },
    {
      id: 'risk-product-focus',
      title: 'Product Dilution',
      description: 'Custom client requests derail roadmap and delay productization.',
      likelihood: 'high',
      impact: 'material',
      mitigation: ['Product council approvals for scope creep', 'Offer premium pricing for bespoke work'],
      contingency: 'Spin up separate client pod dedicated to bespoke projects.',
    },
    {
      id: 'risk-talent-burnout',
      title: 'Delivery Team Burnout',
      description: 'High-intensity services work strains team morale, hurting retention.',
      likelihood: 'medium',
      impact: 'severe',
      mitigation: ['Rotate staffing across project types', 'Institute recovery sprints and wellbeing stipend'],
      contingency: 'Engage fractional specialists and adjust client SLAs.',
    },
  ],
  kpis: [
    {
      id: 'kpi-gm',
      label: 'Service Gross Margin',
      description: 'Gross margin across billable services work.',
      target: '50%+',
      frequency: 'monthly',
      category: 'financial',
    },
    {
      id: 'kpi-client-sat',
      label: 'Client Satisfaction Score',
      description: 'Qualitative survey of client outcomes and renewal intent.',
      target: 'CSAT > 4.5 / 5',
      frequency: 'monthly',
      category: 'operational',
    },
    {
      id: 'kpi-delivery-cycle',
      label: 'Delivery Cycle Time',
      description: 'Average weeks to complete a core engagement.',
      target: '< 6 weeks',
      frequency: 'monthly',
      category: 'operational',
    },
    {
      id: 'kpi-product-adoption',
      label: 'Product Feature Adoption',
      description: 'Percentage of service clients actively using product modules.',
      target: '60% adoption',
      frequency: 'monthly',
      category: 'product',
    },
    {
      id: 'kpi-recurring-revenue-share',
      label: 'Recurring Revenue Share',
      description: 'Share of revenue coming from retainers or subscriptions.',
      target: '35% of total revenue',
      frequency: 'monthly',
      category: 'financial',
    },
    {
      id: 'kpi-churn',
      label: 'Client Churn Rate',
      description: 'Rolling 3-month churn on retainer or subscription clients.',
      target: '<5% churn',
      frequency: 'monthly',
      category: 'growth',
    },
    {
      id: 'kpi-mrr-hybrid',
      label: 'Hybrid MRR',
      description: 'Monthly recurring revenue from software plus service augmentations.',
      target: '$100k MRR',
      frequency: 'monthly',
      category: 'financial',
    },
    {
      id: 'kpi-software-margin',
      label: 'Software Gross Margin',
      description: 'Gross margin specific to the software component.',
      target: '70%+',
      frequency: 'monthly',
      category: 'financial',
    },
  ],
  comparisonScores: [
    {
      metricId: 'time-to-revenue',
      rationale: 'Billable services produce revenue from month one.',
      dimensionScores: {
        speed: 4.5,
        efficiency: 3.6,
        complexityInverse: 3.4,
        downsideInverse: 3.1,
        upside: 3.8,
      },
    },
    {
      metricId: 'capital-efficiency',
      rationale: 'Low upfront investment with service cash flow underwriting product build.',
      dimensionScores: {
        speed: 4.0,
        efficiency: 4.4,
        complexityInverse: 3.1,
        downsideInverse: 3.2,
        upside: 3.9,
      },
    },
    {
      metricId: 'operating-complexity',
      rationale: 'Requires balancing utilization, product roadmap, and client management.',
      dimensionScores: {
        speed: 3.4,
        efficiency: 3.5,
        complexityInverse: 3.0,
        downsideInverse: 3.0,
        upside: 3.7,
      },
    },
    {
      metricId: 'downside-protection',
      rationale: 'Services revenue cushions volatility but pipeline risk remains.',
      dimensionScores: {
        speed: 3.8,
        efficiency: 3.6,
        complexityInverse: 3.2,
        downsideInverse: 3.4,
        upside: 3.5,
      },
    },
    {
      metricId: 'upside-potential',
      rationale: 'Upside depends on successfully transitioning to software-led economics.',
      dimensionScores: {
        speed: 3.5,
        efficiency: 3.9,
        complexityInverse: 3.0,
        downsideInverse: 3.3,
        upside: 4.1,
      },
    },
  ],
  checklist: [
    {
      id: 'chk-offering-design',
      label: 'Signature Offering Designed',
      description: 'Define ICP, promise, pricing, and deliverables with supporting assets.',
      owner: 'Founder',
      stage: 'pre-launch',
    },
    {
      id: 'chk-delivery-os',
      label: 'Delivery Operating System',
      description: 'Centralized project management, QA, and documentation workflows.',
      owner: 'Delivery Lead',
      stage: 'build',
    },
    {
      id: 'chk-hybrid-pricing',
      label: 'Hybrid Pricing Launched',
      description: 'Introduce bundles mixing services and recurring product access.',
      owner: 'Revenue Lead',
      stage: 'scale',
    },
    {
      id: 'chk-product-spinout',
      label: 'Spin-Out Readiness',
      description: 'Establish go-to-market plan and resource model for product-focused growth.',
      owner: 'Product Lead',
      stage: 'exit',
    },
  ],
  calculators: [
    {
      id: 'calc-utilization',
      title: 'Utilization & Capacity Planner',
      description: 'Plan team utilization across services and product development time.',
      inputs: [
        {
          id: 'input-billable-hours',
          label: 'Billable Hours Available',
          description: 'Total monthly hours across delivery team available for client work.',
          defaultValue: 640,
          unit: 'hours',
        },
        {
          id: 'input-target-utilization',
          label: 'Target Utilization',
          description: 'Desired percentage of time spent on billable work.',
          defaultValue: 0.7,
          min: 0.5,
          max: 0.85,
        },
        {
          id: 'input-product-allocation',
          label: 'Product Allocation Hours',
          description: 'Monthly hours reserved for internal product development.',
          defaultValue: 160,
          unit: 'hours',
        },
      ],
      scenarios: [
        {
          id: 'scenario-revenue-capacity',
          label: 'Revenue Capacity',
          description: 'Projected revenue considering utilization and blended rate.',
          formula: '(billableHours * targetUtilization * blendedRate)',
        },
        {
          id: 'scenario-product-bandwidth',
          label: 'Product Bandwidth',
          description: 'Remaining capacity for product sprints after meeting client commitments.',
          formula: 'productAllocationHours - (billableHours * (1 - targetUtilization))',
        },
      ],
    },
  ],
  exitCriteria: {
    strategic: [
      'Product contributes majority of gross profit with proven low-churn channels.',
      'Repeatable customer archetype with case studies showing hybrid success.',
    ],
    financial: [
      '$1.5M+ ARR equivalent with 20% EBITDA margin including services.',
      'Software gross margin consistently above 70%.',
    ],
    triggerToReevaluate: [
      'Service revenue remains >75% after month 18 with limited product traction.',
      'Team utilization below 60% for two consecutive quarters.',
    ],
  },
  budgetTimeline: [
    {
      phaseId: 'service-design',
      timeline: 'Months 0-3',
      granularity: 'month',
      burnRate: 32000,
      notes: 'Client acquisition spend and upfront tooling.',
    },
    {
      phaseId: 'tooling-incubation',
      timeline: 'Months 3-9',
      granularity: 'month',
      burnRate: 36000,
      notes: 'Balancing delivery headcount with initial product engineering.',
    },
    {
      phaseId: 'hybrid-scale',
      timeline: 'Months 9-18',
      granularity: 'month',
      burnRate: 42000,
      notes: 'Investment in marketing, customer success, and usage analytics.',
    },
    {
      phaseId: 'product-spinout',
      timeline: 'Months 18-30',
      granularity: 'month',
      burnRate: 39000,
      notes: 'Product hires, support resources, and go-to-market automation.',
    },
  ],
  supportingCopyIds: ['founderFit', 'capitalDiscipline'],
};
