import { StrategicPlan } from '../types';

export const microPeRollUpPlan: StrategicPlan = {
  id: 'micro-pe-roll-up',
  title: 'Micro-PE Roll-Up Fund',
  subtitle: 'Acquire and compound niche digital assets under a centralized operational playbook.',
  summary:
    'Target multiple <$1M EBITDA software and service assets, standardize operations, and drive multiple expansion through bundled offerings and shared services.',
  idealFounderProfile: [
    'Operator with M&A transaction experience and disciplined underwriting instincts',
    'Revenue leader capable of cross-selling across a shared customer base',
    'Finance partner comfortable with debt structures and integration modeling',
  ],
  capitalAllocations: [
    {
      category: 'Acquisition Equity',
      description: 'Equity checks for three to five initial acquisitions with seller rollovers.',
      amount: 320000,
      percentage: 45,
    },
    {
      category: 'Integration & Shared Services',
      description: 'Standing up centralized marketing, success, and finance pods.',
      amount: 170000,
      percentage: 24,
    },
    {
      category: 'Working Capital & Debt Service Reserve',
      description: 'Interest reserves, covenant buffers, and contingency for underperformance.',
      amount: 120000,
      percentage: 17,
    },
    {
      category: 'Platform Build & Analytics',
      description: 'Shared data warehouse, KPI instrumentation, and automation tooling.',
      amount: 100000,
      percentage: 14,
    },
  ],
  phases: [
    {
      id: 'fund-setup',
      title: 'Fund Formation & Deal Pipeline',
      duration: 'Months 0-4',
      focus: 'Structure fund vehicle, recruit LP capital, and cultivate proprietary deal flow.',
      objectives: [
        'Finalize legal structure and banking relationships for acquisitions.',
        'Build vetted pipeline of 40+ actionable targets with seller motivation scored.',
      ],
      milestones: [
        'Soft commitments covering 120% of planned equity deployment.',
        'Data room standardized for diligence and investor updates.',
      ],
      kpisTracked: ['kpi-lp-commitments', 'kpi-deal-pipeline'],
    },
    {
      id: 'first-close',
      title: 'First Close & Anchor Acquisition',
      duration: 'Months 4-9',
      focus: 'Execute first acquisition and implement integration playbook.',
      objectives: [
        'Close anchor deal with seller rollover and clear expansion levers.',
        'Stand up shared services team covering finance, revops, and lifecycle marketing.',
      ],
      milestones: [
        'Anchor asset stabilized with 10% EBITDA uplift in first 90 days.',
        'Integration scorecard in place across operations, product, and GTM.',
      ],
      kpisTracked: ['kpi-ebitda-uplift', 'kpi-integration-score'],
    },
    {
      id: 'portfolio-scaling',
      title: 'Portfolio Scaling & Cross-Sell',
      duration: 'Months 9-24',
      focus: 'Acquire add-on targets and drive cross-portfolio revenue programs.',
      objectives: [
        'Close 2-3 tuck-in deals with strong product adjacency.',
        'Launch bundled pricing, shared demand gen campaigns, and upsell cadences.',
      ],
      milestones: [
        'Portfolio EBITDA doubles from base year while maintaining 25% margins.',
        'Customer overlap initiative driving 18% blended upsell rate.',
      ],
      kpisTracked: ['kpi-portfolio-ebitda', 'kpi-cross-sell'],
    },
    {
      id: 'exit-readiness',
      title: 'Exit Readiness & Recapitalization',
      duration: 'Months 24-36',
      focus: 'Package platform for strategic sale or recap with institutional investor.',
      objectives: [
        'Demonstrate durable growth with audited financials and SaaS metrics.',
        'Negotiate recapitalization options to return capital while retaining upside.',
      ],
      milestones: [
        'Data room includes QoE, cohort analyses, and integration dashboards.',
        'Run-rate EBITDA > $3.5M with 90%+ recurring revenue mix.',
      ],
      kpisTracked: ['kpi-run-rate-ebitda', 'kpi-recurring-revenue-mix'],
    },
  ],
  pros: [
    'Immediate cash flow visibility with controllable operational levers.',
    'Multiple expansion through platform premium and diversified revenue.',
    'Seller rollovers align incentives and de-risk integration.',
  ],
  cons: [
    'Complex deal execution with legal, tax, and debt counterparties.',
    'Integration missteps can erode synergies and culture quickly.',
    'Requires relentless reporting discipline to satisfy lenders and LPs.',
  ],
  risks: [
    {
      id: 'risk-deal-sourcing',
      title: 'Deal Sourcing Drought',
      description: 'Limited pipeline of quality assets stalls deployment cadence.',
      likelihood: 'medium',
      impact: 'material',
      mitigation: ['Develop broker relationships', 'Fund outbound sourcing team'],
      contingency: 'Pause management fees and extend runway until pipeline replenishes.',
    },
    {
      id: 'risk-integration',
      title: 'Integration Fatigue',
      description: 'Teams resist centralized processes leading to fragmented execution.',
      likelihood: 'medium',
      impact: 'severe',
      mitigation: ['Create 90-day integration scorecards', 'Deploy shared OKRs early'],
      contingency: 'Retain interim integration lead to reset governance.',
    },
    {
      id: 'risk-debt-covenant',
      title: 'Debt Covenant Breach',
      description: 'Underperformance triggers lender remedies and limits flexibility.',
      likelihood: 'low',
      impact: 'severe',
      mitigation: ['Maintain 9-month interest reserve', 'Model downside scenarios quarterly'],
      contingency: 'Pre-negotiate covenant cure rights and standby equity lines.',
    },
  ],
  kpis: [
    {
      id: 'kpi-lp-commitments',
      label: 'LP Commitments Secured',
      description: 'Percentage of target equity capital committed by limited partners.',
      target: '120% soft circled',
      frequency: 'monthly',
      category: 'financial',
    },
    {
      id: 'kpi-deal-pipeline',
      label: 'Qualified Deal Pipeline',
      description: 'Number of vetted acquisition targets in live diligence.',
      target: '12 active deals',
      frequency: 'monthly',
      category: 'growth',
    },
    {
      id: 'kpi-ebitda-uplift',
      label: 'Post-Close EBITDA Uplift',
      description: 'Percentage increase in EBITDA 90 days post acquisition.',
      target: '10% uplift',
      frequency: 'quarterly',
      category: 'financial',
    },
    {
      id: 'kpi-integration-score',
      label: 'Integration Scorecard Completion',
      description: 'Percentage completion of integration milestones on schedule.',
      target: '90%+ completed on time',
      frequency: 'monthly',
      category: 'operational',
    },
    {
      id: 'kpi-portfolio-ebitda',
      label: 'Portfolio EBITDA',
      description: 'Aggregate EBITDA across acquired companies.',
      target: '$3.5M run-rate',
      frequency: 'monthly',
      category: 'financial',
    },
    {
      id: 'kpi-cross-sell',
      label: 'Cross-Sell Penetration',
      description: 'Percentage of customers buying at least two portfolio offerings.',
      target: '40% penetration',
      frequency: 'quarterly',
      category: 'growth',
    },
    {
      id: 'kpi-run-rate-ebitda',
      label: 'Run-Rate EBITDA',
      description: 'Projected annualized EBITDA across the roll-up.',
      target: '$4M+',
      frequency: 'quarterly',
      category: 'financial',
    },
    {
      id: 'kpi-recurring-revenue-mix',
      label: 'Recurring Revenue Mix',
      description: 'Share of revenue that is contractual or subscription-based.',
      target: '90% recurring',
      frequency: 'quarterly',
      category: 'financial',
    },
  ],
  comparisonScores: [
    {
      metricId: 'time-to-revenue',
      rationale: 'Immediate revenue post-close but dependent on deal velocity.',
      dimensionScores: {
        speed: 3.5,
        efficiency: 3.0,
        complexityInverse: 2.0,
        downsideInverse: 3.2,
        upside: 4.1,
      },
    },
    {
      metricId: 'capital-efficiency',
      rationale: 'Leverages debt and seller notes; returns governed by disciplined leverage.',
      dimensionScores: {
        speed: 2.8,
        efficiency: 3.8,
        complexityInverse: 1.9,
        downsideInverse: 3.0,
        upside: 4.3,
      },
    },
    {
      metricId: 'operating-complexity',
      rationale: 'Multi-asset coordination introduces reporting, HR, and culture overhead.',
      dimensionScores: {
        speed: 2.4,
        efficiency: 2.9,
        complexityInverse: 1.8,
        downsideInverse: 2.7,
        upside: 4.5,
      },
    },
    {
      metricId: 'downside-protection',
      rationale: 'Asset diversification cushions downside but leverage amplifies misses.',
      dimensionScores: {
        speed: 2.8,
        efficiency: 3.5,
        complexityInverse: 2.2,
        downsideInverse: 3.2,
        upside: 4.0,
      },
    },
    {
      metricId: 'upside-potential',
      rationale: 'Multiple expansion and bundled products create asymmetric upside.',
      dimensionScores: {
        speed: 3.0,
        efficiency: 3.4,
        complexityInverse: 2.1,
        downsideInverse: 3.1,
        upside: 4.6,
      },
    },
  ],
  checklist: [
    {
      id: 'chk-investment-thesis',
      label: 'Investment Thesis Memo',
      description: 'Codify acquisition criteria, risk tolerances, and value creation levers.',
      owner: 'Managing Partner',
      stage: 'pre-launch',
    },
    {
      id: 'chk-integration-pmo',
      label: 'Integration PMO Setup',
      description: 'Establish cadence, tooling, and reporting for post-close integration.',
      owner: 'Integration Lead',
      stage: 'build',
    },
    {
      id: 'chk-shared-services',
      label: 'Shared Services Operationalized',
      description: 'Centralize finance, HR, and lifecycle marketing processes.',
      owner: 'COO',
      stage: 'scale',
    },
    {
      id: 'chk-exit-readiness',
      label: 'Exit Narrative Prepared',
      description: 'Compile buyer list, banker relationships, and positioning materials.',
      owner: 'CEO',
      stage: 'exit',
    },
  ],
  calculators: [
    {
      id: 'calc-deal-model',
      title: 'Acquisition Return Model',
      description: 'Project leveraged acquisition returns with sensitivity bands.',
      inputs: [
        {
          id: 'input-purchase-price',
          label: 'Purchase Price',
          description: 'Enterprise value paid for the target asset.',
          defaultValue: 1800000,
          unit: 'USD',
        },
        {
          id: 'input-seller-rollover',
          label: 'Seller Rollover Percentage',
          description: 'Equity retained by seller in the platform.',
          defaultValue: 0.2,
          min: 0,
          max: 0.5,
        },
        {
          id: 'input-debt-rate',
          label: 'Debt Interest Rate',
          description: 'Weighted average interest rate on acquisition financing.',
          defaultValue: 0.08,
          min: 0.04,
          max: 0.14,
        },
        {
          id: 'input-ebitda-growth',
          label: 'EBITDA Growth Rate',
          description: 'Projected annual EBITDA expansion driven by integration.',
          defaultValue: 0.18,
          min: -0.1,
          max: 0.4,
        },
      ],
      scenarios: [
        {
          id: 'scenario-equity-multiple',
          label: 'Equity Multiple',
          description: 'Total equity value returned relative to initial cash invested.',
          formula: '((purchasePrice * exitMultiple) - debtOutstanding) / equityInvested',
        },
        {
          id: 'scenario-cash-yield',
          label: 'Yearly Cash Yield',
          description: 'Annual cash distributions relative to equity invested.',
          formula: '(ebitda * (1 - reinvestmentRate) - debtService) / equityInvested',
        },
      ],
    },
  ],
  exitCriteria: {
    strategic: [
      'Three or more assets sharing customer base with bundled GTM motion.',
      'Proven integration playbook with documented synergies per acquisition.',
    ],
    financial: [
      'Portfolio EBITDA > $3.5M with debt/EBITDA below 2.5x.',
      'Consistent quarterly distributions to LPs exceeding 8% cash yield.',
    ],
    triggerToReevaluate: [
      'Acquisition pipeline dries up for two consecutive quarters.',
      'Debt covenants approach breach thresholds despite operational fixes.',
    ],
  },
  budgetTimeline: [
    {
      phaseId: 'fund-setup',
      timeline: 'Months 0-4',
      granularity: 'month',
      burnRate: 38000,
      notes: 'Legal formation, diligence tooling, and travel for deal sourcing.',
    },
    {
      phaseId: 'first-close',
      timeline: 'Months 4-9',
      granularity: 'month',
      burnRate: 52000,
      notes: 'Integration hires, diligence costs, and debt financing fees.',
    },
    {
      phaseId: 'portfolio-scaling',
      timeline: 'Months 9-24',
      granularity: 'month',
      burnRate: 61000,
      notes: 'Shared services operating costs and cross-sell program investment.',
    },
    {
      phaseId: 'exit-readiness',
      timeline: 'Months 24-36',
      granularity: 'month',
      burnRate: 47000,
      notes: 'Banker retainers, audit expenses, and data room maintenance.',
    },
  ],
  supportingCopyIds: ['capitalDiscipline', 'toolingStack'],
};
