import { StrategicPlan } from "../types";

export const verticalAiSaasPlan: StrategicPlan = {
  id: "vertical-ai-saas",
  title: "Vertical AI SaaS Platform",
  subtitle: "Specialized automation for a high-value niche with proprietary data loops.",
  summary:
    "Build a workflow-native AI SaaS offering targeting a regulated vertical where automation unlocks clear ROI and data network effects compound defensibility.",
  idealFounderProfile: [
    "Operator with deep domain expertise and pattern recognition for the target industry",
    "Technical co-founder fluent in applied machine learning and workflow automation",
    "Comfort with enterprise procurement and compliance diligence cycles",
  ],
  capitalAllocations: [
    {
      category: "Product & Data Infrastructure",
      description:
        "Foundational platform, integrations, and vertical-specific dataset development.",
      amount: 180000,
      percentage: 40,
    },
    {
      category: "Go-To-Market Experiments",
      description: "Pilots, design partnerships, and field marketing for lighthouse accounts.",
      amount: 90000,
      percentage: 20,
    },
    {
      category: "Specialist Talent",
      description: "Domain experts, customer success, and fractional compliance resources.",
      amount: 110000,
      percentage: 24,
    },
    {
      category: "Runway Buffer & Working Capital",
      description: "Cash reserve for 12-month runway, security audits, and legal.",
      amount: 70000,
      percentage: 16,
    },
  ],
  phases: [
    {
      id: "discovery-and-data",
      title: "Discovery & Data Moat",
      duration: "Months 0-3",
      focus: "Map critical pain points and secure proprietary data partnerships.",
      objectives: [
        "Validate top three workflow automation opportunities with quantified ROI narratives.",
        "Acquire compliant datasets through pilots or revenue-sharing partnerships.",
      ],
      milestones: [
        "Signed data sharing agreements with two lighthouse customers.",
        "First usable labeled dataset covering 50k+ records.",
      ],
      kpisTracked: ["kpi-discovery-calls", "kpi-dataset-size"],
    },
    {
      id: "pilot-and-refinement",
      title: "Pilot Delivery & Refinement",
      duration: "Months 3-8",
      focus: "Deploy limited-scope pilots and harden human-in-the-loop workflows.",
      objectives: [
        "Ship core product modules across ingestion, model inference, and human review.",
        "Deliver quantifiable ROI case studies with two pilot customers.",
      ],
      milestones: [
        "Net promoter score above 40 from pilot champions.",
        "Pilot customers commit to year-one contracts contingent on feature roadmap.",
      ],
      kpisTracked: ["kpi-pilot-conversion", "kpi-model-accuracy"],
    },
    {
      id: "scale-gomotion",
      title: "Scale GTM Engine",
      duration: "Months 8-16",
      focus: "Operationalize sales, customer success, and onboarding automation.",
      objectives: [
        "Standardize implementation playbooks with <30 day time-to-value.",
        "Build partner ecosystem for integrations and compliance audits.",
      ],
      milestones: [
        "Monthly-recurring revenue surpasses $125k with <4% logo churn.",
        "Gross margin >75% with hybrid automation staffing in place.",
      ],
      kpisTracked: ["kpi-mrr", "kpi-gross-margin"],
    },
    {
      id: "defensibility",
      title: "Defensibility & Expansion",
      duration: "Months 16-24",
      focus: "Deepen moat via proprietary insights and cross-sell modules.",
      objectives: [
        "Launch predictive module leveraging accumulated industry benchmarks.",
        "Establish compliance certifications (SOC 2 Type II, industry-specific).",
      ],
      milestones: [
        "Attach rate of add-on modules exceeds 45% across the base.",
        "Net revenue retention maintains 125%+ for three consecutive quarters.",
      ],
      kpisTracked: ["kpi-attach-rate", "kpi-nrr"],
    },
  ],
  pros: [
    "Recurring revenue with expanding dataset moat and high switching costs.",
    "Attractive to strategic acquirers seeking AI capabilities in regulated verticals.",
    "Pricing power through workflow automation that displaces legacy labor spend.",
  ],
  cons: [
    "Lengthy sales cycles require disciplined capital management.",
    "Regulatory diligence and security compliance are resource intensive.",
    "Continuous model monitoring needed to maintain quality and trust.",
  ],
  risks: [
    {
      id: "risk-data-access",
      title: "Data Access Disruption",
      description: "Key datasets sourced through customer agreements could be revoked or limited.",
      likelihood: "medium",
      impact: "material",
      mitigation: ["Negotiate multi-year access terms", "Build anonymized aggregated benchmarks"],
      contingency: "Maintain synthetic data pipeline and backup industry datasets.",
    },
    {
      id: "risk-compliance",
      title: "Compliance Delays",
      description: "Security assessments or regulatory approval cycles stall enterprise deals.",
      likelihood: "medium",
      impact: "severe",
      mitigation: [
        "Budget for third-party audit partners early",
        "Implement automated evidence collection",
      ],
      contingency: "Prioritize mid-market motion while enterprise audit completes.",
    },
    {
      id: "risk-model-drift",
      title: "Model Performance Drift",
      description: "Changes in customer workflows reduce accuracy of AI predictions.",
      likelihood: "low",
      impact: "material",
      mitigation: [
        "Implement continuous evaluation dashboards",
        "Schedule quarterly label refresh cycles",
      ],
      contingency: "Fallback to human-in-the-loop processing until models recalibrate.",
    },
  ],
  kpis: [
    {
      id: "kpi-discovery-calls",
      label: "Qualified Discovery Calls",
      description: "Validated conversations with ICP operators uncovering automation backlog.",
      target: "20 per month",
      frequency: "monthly",
      category: "growth",
    },
    {
      id: "kpi-dataset-size",
      label: "Proprietary Dataset Volume",
      description: "Total labeled records powering core models.",
      target: "250k labeled records",
      frequency: "monthly",
      category: "product",
    },
    {
      id: "kpi-model-accuracy",
      label: "Model Accuracy",
      description: "Precision/recall benchmarks for primary automation tasks.",
      target: "95% precision with 90% recall",
      frequency: "monthly",
      category: "product",
    },
    {
      id: "kpi-pilot-conversion",
      label: "Pilot to Paid Conversion",
      description: "Ratio of pilots that upgrade to annual contracts.",
      target: "60%+ conversion",
      frequency: "quarterly",
      category: "growth",
    },
    {
      id: "kpi-mrr",
      label: "Monthly Recurring Revenue",
      description: "Recurring revenue run-rate across subscription and usage tiers.",
      target: "$250k MRR",
      frequency: "monthly",
      category: "financial",
    },
    {
      id: "kpi-gross-margin",
      label: "Blended Gross Margin",
      description: "Gross margin inclusive of data labeling and automation labor.",
      target: "75%+",
      frequency: "monthly",
      category: "financial",
    },
    {
      id: "kpi-attach-rate",
      label: "Module Attach Rate",
      description: "Proportion of customers purchasing add-on automation modules.",
      target: "45% attach rate",
      frequency: "quarterly",
      category: "growth",
    },
    {
      id: "kpi-nrr",
      label: "Net Revenue Retention",
      description: "Expansion minus churn over 12-month rolling period.",
      target: "125% NRR",
      frequency: "quarterly",
      category: "financial",
    },
  ],
  comparisonScores: [
    {
      metricId: "time-to-revenue",
      rationale: "Enterprise pilots close within 4-6 months with paid expansions by month 9.",
      dimensionScores: {
        speed: 3.8,
        efficiency: 3.2,
        complexityInverse: 2.4,
        downsideInverse: 3.5,
        upside: 4.4,
      },
    },
    {
      metricId: "capital-efficiency",
      rationale: "High upfront build cost offset by strong gross margins post-onboarding.",
      dimensionScores: {
        speed: 3.2,
        efficiency: 3.9,
        complexityInverse: 2.6,
        downsideInverse: 3.3,
        upside: 4.5,
      },
    },
    {
      metricId: "operating-complexity",
      rationale: "Requires multi-disciplinary team spanning ML, compliance, and customer success.",
      dimensionScores: {
        speed: 2.8,
        efficiency: 3.1,
        complexityInverse: 2.2,
        downsideInverse: 3.0,
        upside: 4.7,
      },
    },
    {
      metricId: "downside-protection",
      rationale: "Contracted revenue and sticky workflows provide cushion once deployed.",
      dimensionScores: {
        speed: 3.0,
        efficiency: 3.6,
        complexityInverse: 2.7,
        downsideInverse: 3.9,
        upside: 4.1,
      },
    },
    {
      metricId: "upside-potential",
      rationale: "Vertical expansion and data moats open multi-product suite potential.",
      dimensionScores: {
        speed: 3.2,
        efficiency: 3.5,
        complexityInverse: 2.3,
        downsideInverse: 3.6,
        upside: 4.8,
      },
    },
  ],
  checklist: [
    {
      id: "chk-domain-map",
      label: "Domain Workflow Mapping",
      description: "Document end-to-end process flows with stakeholder interviews.",
      owner: "Founding team",
      stage: "pre-launch",
    },
    {
      id: "chk-data-governance",
      label: "Data Governance Playbook",
      description: "Define retention, anonymization, and access controls for sensitive data.",
      owner: "Head of Data",
      stage: "build",
    },
    {
      id: "chk-scale-support",
      label: "Scalable Support Model",
      description: "Instrument in-app guidance, knowledge base, and escalation paths.",
      owner: "Customer Success Lead",
      stage: "scale",
    },
    {
      id: "chk-exit-materials",
      label: "Exit Narrative Dossier",
      description: "Maintain data room with cohort performance, expansion metrics, and roadmap.",
      owner: "CEO",
      stage: "exit",
    },
  ],
  calculators: [
    {
      id: "calc-pilot-economics",
      title: "Pilot Program Economics",
      description: "Model cash flow impact of running design partner pilots with limited scope.",
      inputs: [
        {
          id: "input-pilot-count",
          label: "Number of Pilots",
          description: "Active design partners running scoped pilots.",
          defaultValue: 3,
          min: 1,
          max: 10,
        },
        {
          id: "input-pilot-cost",
          label: "Pilot Delivery Cost",
          description: "Monthly cost to support each pilot including human-in-the-loop labor.",
          defaultValue: 6000,
          unit: "USD",
        },
        {
          id: "input-conversion-rate",
          label: "Conversion Rate to Paid",
          description: "Percentage of pilots that convert to paid annual contracts.",
          defaultValue: 0.6,
          min: 0,
          max: 1,
        },
        {
          id: "input-annual-contract",
          label: "Average Annual Contract Value",
          description: "Expected ACV for converted pilot accounts.",
          defaultValue: 90000,
          unit: "USD",
        },
      ],
      scenarios: [
        {
          id: "scenario-payback",
          label: "Months to Payback",
          description: "Break-even point on pilot investments once accounts convert.",
          formula:
            "((pilotCount * pilotCost * pilotDurationMonths) - (pilotCount * conversionRate * annualContract / 12)) / monthlyGrossMargin",
        },
        {
          id: "scenario-first-year-profit",
          label: "First-Year Contribution Margin",
          description: "Net contribution from converted pilots after support costs.",
          formula:
            "(pilotCount * conversionRate * annualContract * grossMargin) - (pilotCount * pilotCost * 12)",
        },
      ],
    },
  ],
  exitCriteria: {
    strategic: [
      "Validated product-market fit in core vertical with 30+ paying customers.",
      "Referenceable ROI case studies with quantifiable automation impact.",
    ],
    financial: [
      "$3M+ ARR with 125% net revenue retention and >20% EBITDA margin.",
      "Attach rate above 40% on advanced analytics modules.",
    ],
    triggerToReevaluate: [
      "Sales cycles exceed 9 months with declining conversion rates.",
      "Gross margin dips below 65% for two consecutive quarters.",
    ],
  },
  budgetTimeline: [
    {
      phaseId: "discovery-and-data",
      timeline: "Months 0-3",
      granularity: "month",
      burnRate: 45000,
      notes: "Heavy spend on data acquisition and compliance readiness.",
    },
    {
      phaseId: "pilot-and-refinement",
      timeline: "Months 3-8",
      granularity: "month",
      burnRate: 52000,
      notes: "Pilot delivery and incremental engineering hires.",
    },
    {
      phaseId: "scale-gomotion",
      timeline: "Months 8-16",
      granularity: "month",
      burnRate: 61000,
      notes: "Sales and CS build-out with automation tooling investment.",
    },
    {
      phaseId: "defensibility",
      timeline: "Months 16-24",
      granularity: "month",
      burnRate: 55000,
      notes: "Certifications, advanced R&D, and expansion initiatives.",
    },
  ],
  supportingCopyIds: ["founderFit", "capitalDiscipline", "toolingStack"],
};
